routes/web.php
<?php

use App\Http\Controllers\BookController;
use App\Http\Controllers\Category\CategoryController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group([], function() {
   Route::get('categories', [CategoryController::class, 'index'])->name('categories.index');
   Route::resource('books', BookController::class)->except('show');
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    const COVER_IMAGE_PATH = 'books/cover_image';
    const PDF_PATH = 'books/pdf';
    const STATUS = ['Unpublished', 'Published'];

    protected $fillable = ['user_id', 'category_id', 'name', 'slug', 'description', 'cover_image', 'pdf_file', 'status'];

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getPdfUrlAttribute()
    {
        return asset('uploads/' . self::PDF_PATH . '/' . $this->pdf_file);
    }

    public function getCoverImageUrlAttribute()
    {
        return asset('uploads/' . self::COVER_IMAGE_PATH . '/' . $this->cover_image);
    }

    public function getBookStatusAttribute()
    {
        return self::STATUS[$this->status];
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Book\CreateRequest;
use App\Http\Requests\Book\UpdateRequest;
use App\Models\Book;
use App\Models\Category;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Str;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $books = Book::orderBy('name')->with('category:id,name', 'createdBy:id,name')->get();
        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $categories = Category::select(['id', 'name'])->get();
        return view('books.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $request
     * @return RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        $data = $request->validated();
        $data['slug'] = Str::slug($request->slug);
        $data['cover_image'] = fileUpload($request->cover_image, Book::COVER_IMAGE_PATH, $data['slug']);
        $data['pdf_file'] = fileUpload($request->book_pdf, Book::PDF_PATH, $data['slug']);
        $data['category_id'] = $request->category;
        auth()->user()->books()->create($data);
        session()->flash('success', 'Book created successfully');
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Book $book
     * @return Factory|View
     */
    public function edit(Book $book)
    {
        $categories = Category::select(['id', 'name'])->get();
        return view('books.edit', compact('categories', 'book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateRequest  $request
     * @param Book $book
     * @return RedirectResponse
     */
    public function update(UpdateRequest $request, Book $book)
    {
        $data = $request->validated();
        $data['slug'] = Str::slug($request->slug);
        $data['category_id'] = $request->category;
        if($request->has('cover_image')) $data['cover_image'] = fileUpload($request->cover_image, Book::COVER_IMAGE_PATH, $data['slug'], $book->cover_image);
        if($request->has('book_pdf')) $data['pdf_file'] = fileUpload($request->book_pdf, Book::PDF_PATH, $data['slug'], $book->pdf_file);
        $book->update($data);
        session()->flash('success', 'Book updated successfully');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Book $book
     * @return RedirectResponse
     */
    public function destroy(Book $book)
    {
        unlinkFile($book->cover_image, Book::COVER_IMAGE_PATH);
        unlinkFile($book->pdf_file, Book::PDF_PATH);
        $book->delete();
        session()->flash('success', 'Book deleted successfully');
        return back();
    }
}

resources/views/books/create.blade.php
@extends('layouts.backend')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-6">
                            <h3>{{ __('Add a new Book') }}</h3>
                        </div>
                        <div class="col-6">
                            <a href="{{ route('books.index') }}" class="btn btn-sm btn-outline-info float-right">
                                <i class="fa fa-arrow-left"></i> Back To Index
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('books.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input id="name" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter Name" value="{{ old('name') }}" required/>
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="slug">Slug</label>
                            <input id="slug" name="slug" class="form-control @error('slug') is-invalid @enderror" placeholder="Enter Slug" value="{{ old('slug') }}" required/>
                            @error('slug')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select id="category" name="category" class="form-control @error('category') is-invalid @enderror" required>
                                <option value="">Choose Category</option>
                                @forelse($categories as $category)
                                    <option {{ old('category') == $category->id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                                @empty
                                @endforelse
                            </select>
                            @error('category')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea id="description" name="description" class="form-control @error('description') is-invalid @enderror" placeholder="Enter Description" rows="10" required>{{ old('description') }}</textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="cover_image">Cover Image</label>
                            <input type="file" id="cover_image" name="cover_image" class="form-control-file @error('cover_image') is-invalid @enderror" required/>
                            @error('cover_image')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="book_pdf">Book PDF</label>
                            <input type="file" id="book_pdf" name="book_pdf" class="form-control-file @error('book_pdf') is-invalid @enderror" required/>
                            @error('book_pdf')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        @if(auth()->user()->is_admin)
                            <div class="form-group">
                                <label>Status</label><br>
                                <label>
                                    <input type="radio" name="status" value="0" {{ !old('status') ? 'checked' : '' }}> Unpublished
                                </label>
                                <label>
                                    <input type="radio" name="status" value="1" {{ old('status') ? 'checked' : '' }}> Published
                                </label>
                                @error('status')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        @endif
                        <div class="form-group">
                            <button type="submit" class="btn btn-sm btn-outline-info float-right">
                                <i class="fa fa-check"></i> Submit
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        const nameField = $('#name');
        const slugField = $('#slug');
        nameField.on('keyup', function() {
            const slug = $(this).val()
                .toLowerCase()
                .replace(/[^\w ]+/g, '')
                .replace(/ +/g, '-');
            slugField.val(slug)
        });
    </script>
@endpush

resources/views/books/edit.blade.php
@extends('layouts.backend')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-6">
                            <h3>{{ __('Update Book') }}</h3>
                        </div>
                        <div class="col-6">
                            <a href="{{ route('books.index') }}" class="btn btn-sm btn-outline-info float-right">
                                <i class="fa fa-arrow-left"></i> Back To Index
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('books.update', $book->id) }}" method="post" enctype="multipart/form-data">
                        @csrf @method('put')
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input id="name" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Enter Name" value="{{ old('name', $book->name) }}" required/>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="slug">Slug</label>
                            <input id="slug" name="slug" class="form-control @error('slug') is-invalid @enderror" placeholder="Enter Slug" value="{{ old('slug', $book->slug) }}" required/>
                            @error('slug')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select id="category" name="category" class="form-control @error('category') is-invalid @enderror" required>
                                <option value="">Choose Category</option>
                                @forelse($categories as $category)
                                    <option {{ old('category', $book->category_id) == $category->id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                                @empty
                                @endforelse
                            </select>
                            @error('category')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea id="description" name="description" class="form-control @error('description') is-invalid @enderror" placeholder="Enter Description" rows="10" required>{{ old('description', $book->description) }}</textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="cover_image">Cover Image <span class="text-secondary">( <i>if you want to change</i> )</span></label>
                            <input type="file" id="cover_image" name="cover_image" class="form-control-file @error('cover_image') is-invalid @enderror"/>
                            @error('cover_image')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <br>
                            <img src="{{ $book->cover_image_url }}" alt="{{ $book->name }}" width="64px">
                        </div>
                        <div class="form-group">
                            <label for="book_pdf">Book PDF <span class="text-secondary">( <i>if you want to change</i> )</span></label>
                            <input type="file" id="book_pdf" name="book_pdf" class="form-control-file @error('book_pdf') is-invalid @enderror"/>
                            @error('book_pdf')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        @if(auth()->user()->is_admin)
                            <div class="form-group">
                                <label>Status</label><br>
                                <label>
                                    <input type="radio" name="status" value="0" {{ !old('status', $book->status) ? 'checked' : '' }}> Unpublished
                                </label>
                                <label>
                                    <input type="radio" name="status" value="1" {{ old('status', $book->status) ? 'checked' : '' }}> Published
                                </label>
                                @error('status')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        @endif
                        <div class="form-group">
                            <button type="submit" class="btn btn-sm btn-outline-info float-right">
                                <i class="fa fa-check"></i> Submit
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        const nameField = $('#name');
        const slugField = $('#slug');
        nameField.on('keyup', function() {
            const slug = $(this).val()
                .toLowerCase()
                .replace(/[^\w ]+/g, '')
                .replace(/ +/g, '-');
            slugField.val(slug)
        });
    </script>
@endpush

resources/views/books/index.blade.php
@extends('layouts.backend')

@push('style')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('assets/backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/backend/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-6">
                            <h3>{{ __('Book') }}</h3>
                        </div>
                        <div class="col-6">
                            <a href="{{ route('books.create') }}" class="btn btn-sm btn-outline-info float-right">
                                <i class="fa fa-plus"></i> Add New Book
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered dataTable">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Cover Image</th>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Created By</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($books as $book)
                            <tr>
                                <th>{{ $loop->index + 1 }}</th>
                                <th>
                                    <img src="{{ $book->cover_image_url }}" alt="{{ $book->name }}" width="24px">
                                </th>
                                <th>{{ $book->name }}</th>
                                <th>{{ $book->category->name }}</th>
                                <th>{{ $book->createdBy->name }}</th>
                                <th>{{ $book->book_status }}</th>
                                <th>
                                    <a download href="{{ $book->pdf_url }}" class="btn btn-sm btn-outline-primary">
                                        <i class="fa fa-download"></i>
                                    </a>
                                    <a href="{{ route('books.edit', $book->id) }}" class="btn btn-sm btn-outline-info">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <button type="button" class="btn btn-sm btn-outline-danger delete-confirm" data-action="{{ route('books.destroy', $book->id) }}">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </th>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" class="text-center">No Book Found</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('partials.delete-confirm')
@endsection

@push('script')
    <!-- DataTables -->
    <script src="{{ asset('assets/backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('assets/backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script>
        $(function () {
            $(".dataTable").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
            });
        });
    </script>
@endpush